### ISSUE TITLE
Support invalid usernames

### ISSUE THREAD

**Issue by pomber** [hexacta/sanata#1]
Currently, invalid usernames are returning a 504 error.

For instance: http://sanata-test.hexacta.com/api/model/notavalidtwitterusername

This probably should return a 404, and a friendly message should be displayed to the user.

**Comment by pomber** [comment]
I'll take a look

**Comment by pomber** [comment]
Thanks, you are awesome

**Comment by buglePhotographer** [comment]
Working on this issue.
