### ISSUE TITLE
Generated tweets show &amp; instead of &

### ISSUE THREAD

**Issue by pomber** [hexacta/sanata#9]
See this example from Donald:
> @NancyNielsenn: You will go to Louisiana \&amp; another speech tonight - live on Tuesday, April 5th! MAKE AMERICA SAFE AGAIN!

**Comment by pomber** [comment]
I'm still seeing some &amps:  
![image](https://user-images.githubusercontent.com/1911623/27442649-2ae58c22-5747-11e7-80aa-84083cad6ce0.png)

**Comment by nituguivi** [comment]
I loaded 37 twitts with "&" and I see them as expected.
Do you see some with "&amp" and some with "&" or all with "&amp"?

![image](https://user-images.githubusercontent.com/7329403/27488122-49089e72-580c-11e7-82bb-a5277f275de8.png)

**Comment by pomber** [comment]
My bad. I was running sanata from a PR that doesn't have #23 changes. Sorry!
